### ISSUE TITLE
Update pdb

### ISSUE THREAD

**Issue by calixteman** [getsentry/symbolic#162]
In order to have correct data in debuginfo (https://github.com/willglynn/pdb/commit/df4016c4be9781a7b82ac197eb8445c0fb0765d9), it'd be nice to update the pdb dependency.

**Comment by jan-auer** [comment]
👍 Will do. I'm hoping to get a fix in for https://github.com/willglynn/pdb/issues/63, too.

**Comment by jan-auer** [comment]
Fixed in 129ce823d3631b1ab76b4b73b824ef14dec4f48e
