### ISSUE TITLE
Add the possibility to configure the demangler with all available options

### ISSUE THREAD

**Issue by calixteman** [getsentry/symbolic#163]
Right now, we just have two possibilities: Full  or Short. 
It'd be nice to be able to select the flags we want to demangle.

**Comment by jan-auer** [comment]
Agreed, that would definitely be better. What would be the flags that you'd like to see? 

Challenges for us was the compatibility between the different demanglers used under the hood, specifically the ones not implemented in Rust (which cause a massive pain in maintenance at the moment).

**Comment by calixteman** [comment]
Maybe having something like
```rust
DemangleOption {
  rust: u64,
  msvc: u64, ...
}
```
and some constants we could use with "or" operator would be enough.

**Comment by Swatinem** [comment]
By now we have a few more options here, but I would rather not expose all the implementation details.
I closed #165 for similar reasons.
