### ISSUE TITLE
Can this be a complete replacement for atos?

### ISSUE THREAD

**Issue by yakout** [getsentry/symbolic#171]

**Comment by jan-auer** [comment]
`symbolic` is meant to do exactly this, but we never built a full atos/addr2line CLI on top of symbolic. The example closest to this right now is `symcache_debug`, but that's more an internal utility. 

Many of the lower level functions are already there. However, the `DebugInfo` trait, required to do full symbolication, does not yet expose a function to symbolicate a single address. If I have some more time, I can add it in the future -- and I'm more than happy to accept PRs in this direction :)

**Comment by jan-auer** [comment]
#222 added a very naive `addr2line` implementation. It is still slower than it needs to be since it relies on `DebugSession::functions` instead of doing a direct lookup.

**Comment by Swatinem** [comment]
I will close this, as we have a `addr2line` utility and a `symcache_debug` utility that serve this purpose.
