### ISSUE TITLE
symcache line definition is capping to 65k

### ISSUE THREAD

**Issue by pablomolnar** [getsentry/symbolic#178]
I'm having issues symbolicating files with more than 65k lines like [sqlite3.c](https://raw.githubusercontent.com/qt/qtbase/dev/src/3rdparty/sqlite/sqlite3.c). Everything points to `LineRecord` definition (https://github.com/getsentry/symbolic/blob/master/symcache/src/format.rs#L242) and writer logic (`line: std::cmp::min(line.line, std::u16::MAX.into()) as u16`)  where `u16` should be `u32` instead (https://github.com/getsentry/symbolic/blob/master/symcache/src/writer.rs#L446)

e.g.:

The following symbolicated frame should have line `115772` but it's clipped to `65535`

```json
{
        "abs_path": "../../../../../../../third-party/sqlite3/src/sqlite3.c",
        "base_dir": "../../../../../../../third-party/sqlite3/src",
        "comp_dir": ".",
        "filename": "sqlite3.c",
        "function_name": "sqlite3_exec",
        "instr_addr": 6815687,
        "lang": "c",
        "line": 65535,
        "line_addr": 6815614,
        "rel_path": "../../../../../../../third-party/sqlite3/src/sqlite3.c",
        "sym_addr": 6815388,
        "symbol": "sqlite3_exec"
}
```

**Comment by pablomolnar** [comment]
@jan-auer Any thoughts?

**Comment by mitsuhiko** [comment]
@pablomolnar it's a bit tricky to resolve. We would have to write multiple line records with an offset. Might be worth resolving given the fact that sqlite has a massive file they actually distribute.
