### ISSUE TITLE
Support Code snippets/Context for lua (or any language)

### ISSUE THREAD

**Issue by bsergean** [getsentry/symbolic#197]
Hi there,

We currently have some middle-man service we use to report lua crashes to sentry. That service build a json payload, and look at a companion zip file containing all the source code to set the code snippets/context fields.

We would like to kill that middle-man service, and instead use a 'normal' sentry solution. Up until a certain point, I was thinking about building a fake javascript sourcemap file, and masquerade our lua crash as javascript. Is that viable ? It doesn't sound too good if you guys one day start to parse the source-map files and bail out because the syntax is not javascript.

Do we need a new solution for that use case ? I created the ticket here but maybe it belongs in the sentry project.

Thanks for any pointer !

**Comment by bsergean** [comment]
We figure out a solution, this is possible without any change to sentry.

**Comment by jan-auer** [comment]
For posterity: The workaround for now is to send an event with `"platform": "javascript"` and upload source code as release files using `sentry-cli`.
