### ISSUE TITLE
[debuginfo] Syms are not accessible when they're located in section with NOBITS

### ISSUE THREAD

**Issue by calixteman** [getsentry/symbolic#206]
For example:
```bash
objcopy --only-keep-debug libxul.so libxul.so.dbg
readelf -e libxul.so.dbg | rg '\.text'
```
returns `.text             NOBITS           0000000010524000  00001000`
which means that all symbols in `.text` section aren't accessible using `ElfSymbolIterator` because of:
https://github.com/getsentry/symbolic/blob/master/debuginfo/src/elf.rs#L557.
For information `llvm-objcopy` doesn't replace `PROGBITS` for `.text` section.

**Comment by jan-auer** [comment]
Fix released in 7.3.0. Thanks for the PR!
