### ISSUE TITLE
Compilation is failing when flag -Clink-dead-code is passed to rustc

### ISSUE THREAD

**Issue by calixteman** [getsentry/symbolic#224]
In order to get code coverage, we pass `-Clink-dead-code` in `RUSTFLAGS`.
But swift demangler cpp code contains some unused and undefined functions.
Since `cc` automatically add `-ffunction-sections`, all the unused functions are stripped without `-Clink-dead-code`.
A way to reproduce it is to run `RUSTFLAGS="-Clink-dead-code" cargo test` in `demangle` dir.
The end of the output is:
```bash
...
,-Bdynamic" "-lstdc++" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld : /home/calixte/dev/mozilla/symbolic.calixteman/target/debug/deps/libsymbolic_demangle-4f42e003d6aaaf78.rlib(Context.o) : dans la fonction « swift::Demangle::Context::getModuleName[abi:cxx11](llvm::StringRef) » :
          /home/calixte/dev/mozilla/symbolic.calixteman/demangle/vendor/swift/lib/Demangling/Context.cpp:216 : référence indéfinie vers « swift::Demangle::isSpecialized(swift::Demangle::Node*) »
          /usr/bin/ld : /home/calixte/dev/mozilla/symbolic.calixteman/demangle/vendor/swift/lib/Demangling/Context.cpp:217 : référence indéfinie vers « swift::Demangle::getUnspecialized(swift::Demangle::Node*, swift::Demangle::NodeFactory&) »
          collect2: error: ld returned 1 exit status
```

**Comment by calixteman** [comment]
A good way to avoid such a regression in the future could be to add code coverage for code here.
For example we did it for `dump_syms`:
https://github.com/mozilla/dump_syms/blob/master/.taskcluster.yml#L61-L82
If you're ok with that, I can do it.

**Comment by jan-auer** [comment]
We used to run with code coverage on a few other projects in the past, but it considerably slowed down builds iirc. 

> If you're ok with that, I can do it.

Absolutely! Probably the best place to add this here would be in the Makefile.
