### ISSUE TITLE
Documentation for Python

### ISSUE THREAD

**Issue by ArekPiekarz** [getsentry/symbolic#253]
Does the Python version of symbolic have any documentation? I couldn't find it on https://pypi.org/project/symbolic/ or in the source code. For instance I would like to know how to turn frame information like C++ binary name and address into a source file location with a line number. Is it possible to do?

**Comment by jan-auer** [comment]
You're right, the Python documentation is currently very insufficient. Until we catch up with this, you can have a look at this test for an example of how to symbolicate:

https://github.com/getsentry/symbolic/blob/bc5246b529d3a5c5be48fe46869491bf771f2c53/py/tests/test_symcache.py#L29-L43

It's worth pointing out that `symbolic` does not help you to _locate_ the files. You need a separate system to search them on your machine, potentially by loading a path pointed to in the crash, or by consulting a symbol server.
