### ISSUE TITLE
Symbolic demangle build failed on travis

### ISSUE THREAD

**Issue by sunng87** [getsentry/symbolic#254]
I'm getting this error when compiling symbolic-demangle on travis:

```
  error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "vendor/swift/include" "-DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING=1" "-std=c++14" "-o" "/home/travis/build/sunng87/handlebars-rust/target/debug/build/symbolic-demangle-b3aaf8956174a00b/out/vendor/swift/lib/Demangling/Demangler.o" "-c" "vendor/swift/lib/Demangling/Demangler.cpp" with args "c++" did not execute successfully (status code exit code: 1).
```

You can find full information via this log:
https://travis-ci.org/github/sunng87/handlebars-rust/jobs/707920035

Let me know if you need any more information.

**Comment by jan-auer** [comment]
`symbolic-demangle` requires a C++14 compiler. I believe that the default on Travis is not. You can override this by setting:

```yaml
env: CXX=clang++
```

**Comment by jan-auer** [comment]
The compiler is only required for swift support, so I believe we can make this a feature flag in the next major release. If it helps, I can add it as default feature now, so that libraries like `pprof` can turn this feature off.

**Comment by sunng87** [comment]
@jan-auer Thank you for quick response. Adding the env has fixed the issue for me. I agree feature flags are welcomed.
