### ISSUE TITLE
symbolic fails lookup if the lookup address doesn't line up exactly with line record

### ISSUE THREAD

**Issue by willkg** [getsentry/symbolic#285]
When symbolic looks up 0x3c105a1 in `xul.pdb/88FD491257B2E0F54C4C44205044422E1`, it fails the lookup, but it should return `Interpret(JSContext*, js::RunState&)`.

The sym file is at: https://symbols.mozilla.org/xul.pdb/88FD491257B2E0F54C4C44205044422E1/xul.sym

Here's the relevant bits in the sym file:

```
MODULE windows x86_64 88FD491257B2E0F54C4C44205044422E1 xul.pdb
INFO CODE_ID 5ED439916EB4000 xul.dll
...
FILE 16693 hg:hg.mozilla.org/mozilla-central:js/src/vm/Interpreter.cpp:e4b11f027efc1f8c2710ae3f52487a8f10a8fb39
...
FUNC 3c01d20 1f6e8 0 Interpret(JSContext*, js::RunState&)
...
3c104e1 c 3021 16693
3c104ed 10 3070 16693
3c104fd e2 3071 16693
3c105df 10 3076 16693
3c105ef 9 3077 16693
3c105f8 c 3078 16693
3c10604 20 3079 16693
```

Breakpad stackwalker returns `Interpret(JSContext*, js::RunState&)` at `js/src/vm/Interpreter.cpp:3071`.

**Comment by jan-auer** [comment]
Thanks for reporting this, @willkg. I'll take a look at this.

**Comment by willkg** [comment]
Thank you! If there's anything I can do to clarify things, let me know.

**Comment by jan-auer** [comment]
This is a bug in symcache generation. The function record is created with a length of `0`, most likely due to a bug in the loop here:

https://github.com/getsentry/symbolic/blob/86279cb3206d507fee4a9b68e362225cd4fe1df9/symbolic-symcache/src/writer.rs#L500

**Comment by willkg** [comment]
Thank you!
