### ISSUE TITLE
Python wheel for macOS Big Sur

### ISSUE THREAD

**Issue by indragiek** [getsentry/symbolic#301]
Would be great to have a Python wheel for macOS 11.0 to avoid compiling from source. Thank you!

**Comment by jan-auer** [comment]
Actually, I believe this may be a PIP bug. Can you try to upgrade pip to at least 20.3.1 and try again?

While testing the macos_11_0 wheel build, I noticed that with pip 20.2.4 I had the same problem, but 20.3.1 would install the `macosx_10_15_x86_64` wheel just fine.

**Comment by indragiek** [comment]
@jan-auer can confirm that the newer pip version works, feel free to close this in that case!

**Comment by jan-auer** [comment]
Thank you!
