### ISSUE TITLE
memmap unmaintained

### ISSUE THREAD

**Issue by extrawurst** [getsentry/symbolic#304]
`cargo audit` flagged `memmap` as unmaintained and in my `gitui` project this in in the dependency tree because `symbolic` is using it: https://github.com/extrawurst/gitui/issues/435

are you guys planning on migrating away from `memmap`?

see relevant issue on memmap repo: https://github.com/danburkert/memmap-rs/issues/90

**Comment by mitsuhiko** [comment]
There is currently no good reason to migrate off it. The crate is very stable and does what it should do for us. If some other crate were to displace it we would reevaluate.

**Comment by extrawurst** [comment]
@mitsuhiko actually there is a crate to displace it: https://github.com/RazrFalcon/memmap2-rs

**Comment by mitsuhiko** [comment]
That crate existed for barely any time. What guarantees that the crate will survive? Do we trust the author etc.

There is no reason to move off a working crate to a random fork on a whim.
