### ISSUE TITLE
pip install symbolic --no-binary :all: fails due to missing files

### ISSUE THREAD

**Issue by alagendijk-minddistrict** [getsentry/symbolic#309]
Installing symbolic (8.0.1) from pypi with the `--no-binary :all:` option fails during the cargo build phase.
I took a look in the symbolic-8.0.1.zip file from pypi and it looks to me that the rustsrc.zip file in that zip file is missing the files for the git submodules in symbolic-minidump/third_party and because there is also no .git directory it can't pull those in itself.

error message:
```
   error: failed to run custom build command for `symbolic-minidump v8.0.1 (/tmp/tmp95tqdasf/rustsrc/symbolic-minidump)`

    Caused by:
      process didn't exit successfully: `/tmp/tmp95tqdasf/rustsrc/target/release/build/symbolic-minidump-2bc92356db4a663e/build-script-build` (exit code: 101)
      --- stderr
      fatal: not a git repository (or any of the parent directories): .git
      thread 'main' panicked at 'Failed to install git submodules', symbolic-minidump/build.rs:12:13
```

**Comment by jan-auer** [comment]
Thank you, this has been broken since 8.0.0. The sub-directories `third_party/{breakpad,lss}` should be part of the rustsrc.zip bundle.
