### ISSUE TITLE
symcache FuncRecord parent offset is capping to 65k

### ISSUE THREAD

**Issue by wyxloading** [getsentry/symbolic#330]
I'm having issues extracting symcache from pdb which in`parent_offset` larger than `u16`. It points to FuncRecord definition https://github.com/getsentry/symbolic/blob/461173aa47f7b21454158b427c9b80410738aac5/symbolic-symcache/src/format.rs#L207 and write logic https://github.com/getsentry/symbolic/blob/461173aa47f7b21454158b427c9b80410738aac5/symbolic-symcache/src/writer.rs#L660-L662

We expect to support 32 / 64 platform only, so it would be ok to use a u32 parent_offset instead. But it's hard to make a backwards compatible modification since we already have many symcache files extracted in u16 size.

**Comment by jan-auer** [comment]
To confirm: `parent_offset` is the offset of the item index in the functions list between an inline function and its direct parent. To exceed this index, you'd need to have a function with >65k inlinees. Are you certain you'll need a `u32` here?

It is possible to create a backwards incompatible change using the version in the header. However, SymCaches are only meant to be caches, unlike Breakpad symbols. We usually re-compute them on the fly when the version changes and never read old versions.

**Comment by wyxloading** [comment]
> To exceed this index, you'd need to have a function with >65k inlinees. Are you certain you'll need a u32 here?

Yes. We find these cases in the production environment.

> We usually re-compute them on the fly when the version changes and never read old versions.

Sure this will work. I'm wondering any ways that we can skip re-computing latest version symcaches since it still work well besides those "a function with >65k inlinees" cases
