### ISSUE TITLE
Using symbolic-unwind in Breakpad

### ISSUE THREAD

**Issue by loewenheim** [getsentry/symbolic#335]
`symbolic-unwind` provides facilities to parse and evaluate Breakpad RPN expressions. These expressions are used in Breakpad to find the values of registers in previous call frames. For CFI records, they're currently handled as follows:

- The relevant classes are `SourceLineResolverBase` (and its children `BasicSourceLineResolver` and `FastSourceLineResolver`) and `CFIFrameInfo`. `SourceLineResolverBase` has a method `FindCFIFrameInfo` that reads a `CFIFrameInfo` object from a `StackFrame`. This method is specified by `SourceLineResolverInterface`.
- `SourceLineResolverBase` has a method `ParseCFIRuleSet` that parses rules from a String into a `CFIFrameInfo` object. The actual parsing is performed by a `CFIRuleParser`. It's important to note that “parsing” in this context does not refer to creating an AST; the rules are saved as strings.
- `CFIFrameInfo` has a method `FindCallerRegs` that, given a map of current register values and a memory region, outputs the values of the parent frame's registers in the form of another map. It accomplishes this by using `PostfixEvaluator` internally.

This boils down to three things that need doing:
1. There is no way around subclassing `CFIFrameInfo` if we want to implement `SourceLineResolverInterface`. The interface specifies that a `SourceLineResolver` must produce a `CFIFrameInfo`, which in turn is responsible for evaluating expressions. Therefore we need a subclass, say `SymbolicCFIFrameInfo`, that uses our evaluator instead of Breakpad's.
2. We need a custom `SourceLineResolver` that returns a `SymbolicCFIFrameInfo`. Inheriting from `SourceLineResolverBase` may or may not make sense depending on how much functionality that isn't immediately related to CFI records we can reuse.
3. Symbolic's `Evaluator` needs a C++-friendly interface. I've kicked around some ideas for what that might look like, but haven't settled on anything yet. Actually creating the bindings can be done e.g. with the `cbindgen` tool or the `cxx` crate—I've fooled around with both but can't draw any firm conclusions about which is better. This interface may also necessitate changes to `Evaluator`'s design.

All of the above *probably* applies mutatis mutandis to Windows records as well, but I haven't looked at them in too much detail yet.

**Comment by loewenheim** [comment]
An additional question that just occurred to me: Our parser parses expressions into an AST. `CFIFrameInfo` is designed in such a way that it saves the expressions needed to recover each register in string form. How do we square this? Do we expose the `Expr` type to C++ (assuming this is even possible) and have `SymbolicCFIFrameInfo` save `Expr`s instead? The quick and dirty way would be to use our parser to obtain an AST and then giving `SymbolicCFIFrameInfo` the AST's string representation. Which means that we would have to parse it *again* when we evaluate it.

**Comment by luser** [comment]
Counterpoint: #375. Now that @Gankra has pushed the `minidump` crates to feature-parity with Breakpad, I think you'd be better off replacing the use of Breakpad in `symbolic-minidump` with `minidump-processor` and then figuring out the plumbing to do what you want here. (Changes to the `minidump-processor` APIs to make this easier would be welcomed!)

**Comment by Swatinem** [comment]
This ain’t gonna happen no more ;-)
