### ISSUE TITLE
Support DWARF in PE

### ISSUE THREAD

**Issue by jan-auer** [getsentry/symbolic#352]
Potential downstream consumer of this is https://github.com/mozilla/dump_syms/issues/224

Older Rust compiler versions also used to output DWARF sections in PE.

**Comment by mati865** [comment]
> Older Rust compiler versions also used to output DWARF sections in PE.

It's not related to the version but the target. `i686-pc-windows-gnu` produces PE with Dwarf 2 and it's unlikely to change.
