### ISSUE TITLE
Any plan to support Swift 5.3.2？

### ISSUE THREAD

**Issue by highlystuff** [getsentry/symbolic#358]
the following symbol cannot be symbolicated:
$s6BNFeed19BNPodcastHeaderViewC5setup33_A9014F92DDA8A9F90EC0C098E95C2426LLyyFy7SnapKit15ConstraintMakerCXEfU4

**Comment by Swatinem** [comment]
Indeed, with the added underscore, things demangle just fine.
We updated to Swift 5.5 some time ago so I will call this done.
