### ISSUE TITLE
Splitting of >65k functions in symcache format creates incorrect symbol addresses

### ISSUE THREAD

**Issue by mstange** [getsentry/symbolic#405]
### Environment

We use the symbolic Python API to look up addresses in a symcache, here: https://github.com/mozilla-services/tecken/blob/b0ab02f87626531dae3123bb71652b0cf0779ef5/eliot-service/eliot/symbolicate_resource.py#L409-L428

### Steps to Reproduce

```
% cd symbolic
% wget -o XUL.sym.gz https://symbols.mozilla.org/XUL/395F7EC110E43068A7EE11BEA458C5210/XUL.sym
% gzip -d XUL.sym.gz
% cargo run --release -p symcache_debug -- -d XUL.sym -w -c long-drawquad-xul.symcache
% cargo run --release -p symcache_debug -- -c long-drawquad-xul.symcache --symbols | grep draw_quad_spans
```

### Expected Result

There should only be one symbol for the function `void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned int, glsl::vec3*, Texture&, Texture&, ClipRect const&)`, at address 0x39bce0.
Or at least, looking up an address anywhere inside the function should return a result with symbol address 0x39bce0.

### Actual Result

There are three symbols for this function:

```
          39bce0 void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned int, glsl::vec3*, Texture&, Texture&, ClipRect const&)
          3abdc3 void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned int, glsl::vec3*, Texture&, Texture&, ClipRect const&)
          3bbe06 void draw_quad_spans<unsigned int>(int, glsl::vec2_scalar*, unsigned int, glsl::vec3*, Texture&, Texture&, ClipRect const&)
```

Looking up address 0x3b7b74 returns a result with symbol address 0x3abdc3. But in reality there is no symbol at 0x3abdc3 - the function starts at 0x39bce0.

### Debugging

`draw_quad_spans` is a very long function. It goes from 0x39bce0 to 0x3ca0cc, that's 189 420 bytes.
The symcache writer splits up functions whose length does not fit into a u16, here:

https://github.com/getsentry/symbolic/blob/49bd892c2efbfcf502d20164dac942101ddb43cb/symbolic-symcache/src/writer.rs#L484-L491

It would be great if this could be done in a way that doesn't invent new symbol addresses.

### Why is this important

In the Mozilla symbolication API we calculate a "function offset" for each address that gets looked up: this is the offset between the function start and the address.
In the Firefox profiler we group functions that start at the same address into the same call node.

In the future, we want to show an assembly view in the Firefox profiler. This assembly view should show the assembly code of the entire function. It also needs to start at a valid instruction address.
If the function is split, this means that the assembly view would not be able to show the entire function; it would only show an arbitrary 65k excerpt of it. And it might even have trouble disassembling the machine code because the synthetic symbol address might not fall on an instruction boundary.

**Comment by Swatinem** [comment]
Just to give you a bit of a heads-up.
We will be looking into updating the symcache format, and have it revolve around the actual instruction offsets. That rework should solve this and all kinds of other problems that we saw over time. However I can’t give any timeline for that yet.

**Comment by mstange** [comment]
Thanks for the head-up, Arpad. That sounds good, but I wonder if there's a backwards-compatible way to make large functions work with the current format. For example, maybe we could say "if the size is between 0 and UINT16_MAX - 1, it's correct. If it is UINT16_MAX then this function needs to be merged with the next one".
