### ISSUE TITLE
Include dynamic symbols when dealing with ELF files

### ISSUE THREAD

**Issue by gabrielesvelto** [getsentry/symbolic#420]
When dealing with ELF files symbolic-debuginfo [only exposes debug symbols](https://github.com/getsentry/symbolic/blob/67b4cffb6d6d22e4d6a6eb2b87823ca71aa3032b/symbolic-debuginfo/src/elf.rs#L215-L228). This has two drawbacks:
* It's inconsistent with the PE/PDB implementation. Object will still expose public symbols in a bare PE w/o debugging information, but on a stripped ELF file it won't expose any.
* It might cause symbols that are present both as debug symbols and dynamic symbols to have the wrong name, as the names for the latter will be in the dynamic string table. I've noticed this in non-stripped versions of libxul.so where a symbol with the same name would appear at two different addresses. I originally thought this was because the function had been split in hot/cold parts or something along the lines, but as it turns out the other instance was the address of a dynamic symbol with a different name in the dynamic string table.

I've got a crude PR that addresses this, I will post it shortly for feedback.

**Comment by relaxolotl** [comment]
Looks like this was resolved in #421.
