### ISSUE TITLE
Some pdb functions are missing arguments

### ISSUE THREAD

**Issue by mstange** [getsentry/symbolic#423]
When looking up functions in pdb files, some functions are missing their argument types.
For example, you get `_except_handler4` instead of `_except_handler4(_EXCEPTION_RECORD*, _EXCEPTION_REGISTRATION_RECORD*, _CONTEXT*, void*)`, and `is_potentially_valid_image_base` instead of `is_potentially_valid_image_base(void* const)`.

This happens for inlined functions, and for procedures whose argument list is stored in the type info (and for which there is no public symbol at the same address with a mangled name).

### Steps to Reproduce

One way to reproduce this is using the addr2line example from the symbolic repo. Strictly speaking, you might expect it to print no arguments because [it uses `name_only()`](https://github.com/getsentry/symbolic/blob/4e3dc0a9f211588b140bdf3fdf1658fcab8cefcf/examples/addr2line/src/main.rs#L15) when demangling, but for these functions the name is not mangled anyway.

```
% cargo run --release -p addr2line -- -Cfi -e symbolic-debuginfo/tests/fixtures/crash.pdb 0x355b
_except_handler4
  at ??:0
```

```
% cargo run --release -p addr2line -- -Cfi -e symbolic-debuginfo/tests/fixtures/crash.pdb 0x30bf
is_potentially_valid_image_base
  at f:\dd\vctools\crt\vcstartup\src\utility\utility.cpp:35
__scrt_is_nonwritable_in_current_image
  at f:\dd\vctools\crt\vcstartup\src\utility\utility.cpp:99
```

Looking up the same addresses using [pdb-addr2line](https://github.com/mstange/pdb-addr2line) gives the full arguments:

```
% cargo install --examples pdb-addr2line
% pdb-addr2line -Cfi -e symbolic-debuginfo/tests/fixtures/crash.pdb 0x355b
_except_handler4(_EXCEPTION_RECORD*, _EXCEPTION_REGISTRATION_RECORD*, _CONTEXT*, void*)
??:?
% pdb-addr2line -Cfi -e symbolic-debuginfo/tests/fixtures/crash.pdb 0x30bf
is_potentially_valid_image_base(void* const)
f:\dd\vctools\crt\vcstartup\src\utility\utility.cpp:35
__scrt_is_nonwritable_in_current_image(void const*)
f:\dd\vctools\crt\vcstartup\src\utility\utility.cpp:99
```

**Comment by mstange** [comment]
From the Firefox profiler side, this needs to be addressed before we can switch away from using breakpad .sym files for pdbs.

Fixing this should be a simple matter of using [`TypeFormatter` from the pdb-addr2line crate](https://docs.rs/pdb-addr2line/0.5.0/pdb_addr2line/struct.TypeFormatter.html).

However, there is one slight problem: For users who don't want the arguments, specifying `DemangleOptions::name_only()` won't get rid of the arguments. The decision about whether arguments should be present or not needs to be made at a different time.
This also matters when using symcache files: The setting needs to be known when the symcache is generated from the pdb, not when symbols are extracted from the symcache.

**Comment by mstange** [comment]
@jan-auer I'm willing to work on this, but I would need some guidance for how to handle users who don't want the arguments. Would it be fine to just emit arguments always?

**Comment by Swatinem** [comment]
I think its fine to always emit arguments. We use `complete - return_types` in symbolicator:

https://github.com/getsentry/symbolicator/blob/732ed3b9925fecb4b14941dfcdc4c78ce9919444/crates/symbolicator/src/services/symbolication.rs#L51

And there is more code in sentry to shorten that further.

That being said, I don’t think you mentioned return types in your examples? Am I right to assume that we won’t get those either way?

**Comment by mstange** [comment]
> I think its fine to always emit arguments. We use `complete - return_types` in symbolicator:
> 
> https://github.com/getsentry/symbolicator/blob/732ed3b9925fecb4b14941dfcdc4c78ce9919444/crates/symbolicator/src/services/symbolication.rs#L51

Ah, nice.

> That being said, I don’t think you mentioned return types in your examples?

Heh, good point.
The pdb-addr2line `TypeFormatter` does indeed support return types. But [the `Default::default()` implementation for `TypeFormatterFlags`](https://github.com/mstange/pdb-addr2line/blob/8911809121e55703f71c2337ce176be85eb69bc2/src/type_formatter.rs#L39-L46) specifies `NO_MEMBER_FUNCTION_STATIC`. That was my personal preference, because I find that return types add a lot of noise without providing much value. In a profiler you really want to see the method name relatively close to the beginning of the string. [dump_syms made the same choice.](https://github.com/mozilla/dump_syms/blob/bf7f6bd855eb6ecb233b52bfa7b2c975b7026540/src/windows/types.rs#L61)

So while we could have the return type, I would vote for leaving it out.

**Comment by Swatinem** [comment]
I’m 👍🏻 on this then ;-)

**Comment by mstange** [comment]
Great!

I've started working on this and everything worked great except for cross-module imports, https://github.com/mstange/pdb-addr2line/issues/6 . This was caught in the symbolic test suite. So I'm working on that now.

**Comment by chadwhitacre** [comment]
Moving from `Untriaged` to `In Progress`. 👍
