### ISSUE TITLE
Add support for `INLINE` and `INLINE_ORIGIN` entries when parsing .sym files

### ISSUE THREAD

**Issue by gabrielesvelto** [getsentry/symbolic#432]
Google added support for inlined functions in Breakpad via the `INLINE` and `INLINE_ORIGIN` entries (see [this commit](https://chromium.googlesource.com/breakpad/breakpad/+/4f5b814790301e7b8252535e0732bee11f4bb801) and [this commit](https://chromium.googlesource.com/breakpad/breakpad/+/f0803507950279bd1e48d05f5fb4b4377c2917f7)). Unfortunately they didn't update the documentation. This bug is about supporting them in symbolic-debuginfo.

The records look like this:

`INLINE_ORIGIN <origin_id> <name>`

* `origin_id` identifies the inlined function, Breakpad uses a counter starting at 0 for these IDs and it must be unique
* `name` is the name of the inlined function

`INLINE <inline_nest_level> <call_site_line> <call_site_file_id> <origin_id> <address> <size>`

* `inline_nest_level` is the nesting level, starting at 0 for the outermost function
* `call_site_line` is the line at the call site
* `call_site_file_id` points to the `FILE` entry where this call has been inlined
* `origin_id` points to the corresponding `INLINE_ORIGIN` entry
* `address` is the starting address in the module
* `size` is the function size in the module

`INLINE` entries appear after each `FUNC` entry, describing the functions that have been inlined in there, e.g.

```
FUNC 1000 20 0 foo
INLINE 0 ...
INLINE 1 ...
(more INLINE entries) ...
1000 ... // regular source line data
(more source line entries) ...
FUNC 1020 40 0 bar
INLINE 0 ...
INLINE 1 ...
INLINE 2 ...
1020 ... // regular source line data
etc...
```

One thing worth keeping in mind is that prior to this change .sym files used to have a specific structures WRT the order in which the various entries appeared. This does not appear to be true anymore, specifically [this](https://chromium.googlesource.com/breakpad/breakpad/+/e87bb1b3b480d1e44e6a742b8cc0a1698b98494e) points to the fact that `INLINE_ORIGIN` entries can be mixed up with `FUNC` ones.

**Comment by gabrielesvelto** [comment]
Google changed the upstream format [again](https://chromium.googlesource.com/breakpad/breakpad/+/3846f6d297339c17663d7a797ba481b3411f13ad). I'll look at the changes and update the description.

**Comment by gabrielesvelto** [comment]
Sorry, the format didn't change, it's the previous change that I included in the description, but it's been backed out and then re-applied.

**Comment by gabrielesvelto** [comment]
Google added some documentation to Breakpad about [INLINE_ORIGIN](https://chromium.googlesource.com/breakpad/breakpad/+/HEAD/docs/symbol_files.md#records-3) and [INLINE](https://chromium.googlesource.com/breakpad/breakpad/+/HEAD/docs/symbol_files.md#records-5) records.

**Comment by mstange** [comment]
I've started working on this.
