### ISSUE TITLE
symbolic-debuginfo should have features for the formats

### ISSUE THREAD

**Issue by Jake-Shadle** [getsentry/symbolic#469]
Just for a little context, I'm trying to use symbolic-debuginfo within a program so that we can process wasm binaries, build sourcebundles, and upload them to sentry, rather than rely on sentry-cli.

Right now symbolic-debuginfo has no way to only enable specific formats, which leads to any crate that depends on it to potentially pull in multiple dependencies that they would otherwise never depend on, for formats they don't actually care about. For one easy example, wasm support pulls in both walrus and wasmparser (a very outdated version due to walrus being passively maintained) all for a format that many are not targeting. And the converse applies as well, in our case, we _do_ want the wasm format support, but elf, macho, breakpad, and pdb/pe are all also included which means that goblin, pdb, flate2, regex etc are all pulled in even if we don't care about those formats.

There's also various crates that are included that use default features, leading to unnecessary transitive dependencies/code being compiled that are never used, one such example being zip which by default enables bzip2, even though source bundles are only compressed with deflate.

Anyways, I'm actually planning on doing a PR that addresses this issue, I just wanted to make it to give visibility before the PR in case there is a chance such a PR would not be merged, in which case I'd probably end up copying out the pieces we need for our use case into an internal crate or something.

**Comment by loewenheim** [comment]
Sounds like a good idea, we'd be interested in such a PR.
