### ISSUE TITLE
inline function size calculated for multi ranges is too large

### ISSUE THREAD

**Issue by shuoli84** [getsentry/symbolic#521]
I use symbolic debuginfo in rust, with following lines in [debug_info/dwarf.rs](https://github.com/getsentry/symbolic/blob/d3877af86de642c18c799e9ec9c63381c91417f7/symbolic-debuginfo/src/dwarf.rs#L816-L820), the function size is way large than expected. 

```rust
let function_address = offset(range_buf[0].begin, self.inner.info.address_offset);
let function_size = range_buf[range_buf.len() - 1].end - range_buf[0].begin;
let function_end = function_address + function_size;
```

This is the range
```
found it: [Range { begin: 9899400, end: 9899410 }, Range { begin: 9902427, end: 9902445 }]
```

The inlined function is 
```rust
<core::option::Option<bool> as core::clone::Clone>::clone
```

**Comment by shuoli84** [comment]
Is it a good idea we actually fold on each range's size? In this case, it is 
(9899410 - 9899400) + (9902445 - 9902427) = 10 + 18 = 28, instead of 9902445 - 9899410 = 3045

**Comment by shuoli84** [comment]
yea, I am investigating mis-configured inlined functions which caused the binary bloat. E.g, if a function with size larger than 500 bytes is inlined several times, maybe the function's inline hint is wrong.

**Comment by Swatinem** [comment]
Can you give more details? I’m unsure what exactly you mean by "mis-configured inlined functions"?
Is the binary bloat in the original debug file (DWARF) or rather the resulting symcache?

Also, what do you mean by "inline hint" in this case?

**Comment by shuoli84** [comment]
Sure, I am using dwarf info to detect functions which should not be inlined but inlined. 
inline hint is something like rust inline attribute or llvm inline hint. 

E.g:
```rust
#[inline(always)]
fn large_body_fn() {}
```

Not about drawf bloat, drawf info will be stripped.

**Comment by Swatinem** [comment]
Oh, so its more about figuring out how the inliner itself works. I think there is multiple code bloat analysis tools which might be better suited for this though.

**Comment by shuoli84** [comment]
I am writing a debugging tool in rust with this crate, inline analysis is part of it, still some other features requires symbolic crate. Also I think wrong info is misleading, we should fix it? Btw, I am happy to fire a PR :)

**Comment by Swatinem** [comment]
Ah okay that makes sense. Fixing this is definitely a good idea.
Though I’m not sure what the best approach would be tbh. A function `size` does not really make much sense if you have split functions, or inlinees that cover multiple non-contiguous ranges.

**Comment by shuoli84** [comment]
yea, I guess that's why the dwarf info for inline function is ranges. Is it a good idea to use
```rust
ranges.iter().fold(0, |a, r| a + (r.end - i.start)))
```
is better than current impl. I think for split functions, it is better, but not sure for other cases.

**Comment by Swatinem** [comment]
That might be a sensible thing to do, yes. Make sure to only use valid ranges though, linkers don’t remove the ranges themselves, they just invalidate them by putting in bogus values.

Either way, I think changes the definition to "the number of instruction bytes belonging to this function" is a good idea. Though we have to be a bit cautious, at least the previous symcache format used that size assuming toplevel functions have a single contiguous range. That was the reason the old symcache never supported split toplevel functions.

I don’t think from the top of my head that this information is used outside of the specific function that creates this, but we still should be cautious. Also, I’m not entirely sure if inlinee resolution uses this range. That part of the code is a bit of black magic.

**Comment by Swatinem** [comment]
> What is "split toplevel functions"? Is it something like llvm hot cold split?

Yes, exactly. More generally, it is a non-inlined (toplevel) function that has more than one DWARF range.

**Comment by shuoli84** [comment]
Ok, in that case, I think it is better to unify the function_size to the ranges sum value.
