### ISSUE TITLE
Configurable limits for minidump parsing

### ISSUE THREAD

**Issue by relaxolotl** [getsentry/symbolic#551]
https://github.com/getsentry/symbolic/pull/468 was opened as a result of a need to be able to increase some of the default parsing limits on breakpad to be able to hand minidumps with extremely large amounts of data. It has been closed because the changes are now obsolete as a result of a recent switch to rust-minidump as symbolic's minidump-parsing backend of choice; The PR added configurable toggles to breakpad, which is no longer being used by symbolic.

There remains the question of whether we want such values to be configurable with the new backend (rust-minidump). rust-minidump doesn't actually offer the ability to configure these yet: https://github.com/rust-minidump/rust-minidump/issues/363 currently exists to track this.

cc @jan-auer

**Comment by Swatinem** [comment]
There is an upstream issue for this which is not really high priority.
Other than that, we don’t do any minidump processing in symbolic anymore directly.
