### ISSUE TITLE
consider adding the compact-unwind null opcode hack for arm64?

### ISSUE THREAD

**Issue by Gankra** [getsentry/symbolic#618]
I'm looking into https://github.com/mozilla/dump_syms/issues/402 which I think is probably a consequence of this code:

https://github.com/getsentry/symbolic/blob/6c074ad83f1d38f8585705808b638e5b2d2ad3f9/symbolic-cfi/src/lib.rs#L531-L555

from before #445 landed. If so, that would suggest a bunch of macos arm64 system functions are leaves we're failing to CFI properly when we could. I expect for these functions we can just emit something like `.cfa: $sp .ra: $lr`

**Comment by mstange** [comment]
A valid question to ask here would be "Does a null opcode always mean that the function is a stackless leaf function?"

So far it seems it does - I've had [the same fallback](https://github.com/mstange/framehop/blob/6777199dd0c2c1b3768a4d9e160acd5baa9de4a1/src/aarch64/macho.rs#L16-L19) in perfrecord / framehop for a few months now and so far I haven't run into any trouble with it.
