### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mstange** [getsentry/symbolic#643]
I'm interested in a new symbolic release which includes the support for the new breakpad format, as well as the DWARF + PDB fixes.

I'll start to write up some release notes below.

**Comment by mstange** [comment]
I've put the release notes in CHANGELOG.md instead, #644.

**Comment by Swatinem** [comment]
https://github.com/getsentry/publish/issues/1273 
The release just needs to be approved, though I don’t have the permissions for that
