### ISSUE TITLE
Missing inlinee function names

### ISSUE THREAD

**Issue by gabrielesvelto** [getsentry/symbolic#686]
### Environment

symbolic-debuginfo 9.1.4

### Steps to Reproduce

Grab the following two files:
* [libgcc_s-12-20220819.so.1](https://drive.google.com/file/d/1EAUptI26uZj4i_Cr6-MRZzpRRXZWTlEy/view?usp=sharing)
* [libgcc_s-12-20220819.so.1-12.2.1-2.fc36.x86_64.debug](https://drive.google.com/file/d/1RtaIdepuaefnsUxIF6Mghlnw-KU2dmq-/view?usp=sharing)

Open them via symbolic-debuginfo, in my case I'm using the last version of [dump_syms](https://github.com/mozilla/dump_syms/) to dump the debug information.

### Expected Result

The inlinees in all the functions which have them should have a name.

### Actual Result

All the inlinees have empty names

I'm not sure if this is a bug in symbolic or the debug info is broken, either way it's odd to have an empty name in these functions.

**Comment by gabrielesvelto** [comment]
Digging a bit more into it I think that the entries for the inlinees in the DWARF debug info use `DW_FORM_GNU_strp_alt` forms for the names which means that the actual string should live in an external file IIRC.

**Comment by gabrielesvelto** [comment]
So the .debug file has a `.gnu_debugaltlink` section which points to this file: [gcc-12.2.1-2.fc36.x86_64](https://drive.google.com/file/d/1CB_tmc8z5UgwP2d7K9r1jXW6bRsaWTCi/view?usp=sharing). To the best of my knowledge there's no way in Symbolic to create a debug session that fetches data both from [libgcc_s-12-20220819.so.1-12.2.1-2.fc36.x86_64.debug](https://drive.google.com/file/d/1RtaIdepuaefnsUxIF6Mghlnw-KU2dmq-/view?usp=sharing) and from it, or I'm missing something?

**Comment by jernejstrasner** [comment]
This issue is stale. Closing. Please reopen if necessary.
