### ISSUE TITLE
Issue in UnrealEngine log parsing

### ISSUE THREAD

**Issue by tdesveaux** [getsentry/symbolic#694]
We see some `ERROR_NO_MORE_ITEMS / 0x0` in breadcrumbs and issues for our UE issues.
I'm not fluent in rust but I think I managed to track it to [this](https://github.com/getsentry/symbolic/blob/a562b1e5609f05c91498cb696916693ef6f2ac8e/symbolic-unreal/src/logs.rs#L107) call not parsing the entry correctly (from what I gathered, the breadcrumb is generated from the log file for UE crashes uploaded through the UE CrashReporter).
I opened a [PR](https://github.com/mitsuhiko/rust-anylog/pull/6) on the rust-anylog to fix it so updating the dependency when merged could fix the issue.

**Comment by loewenheim** [comment]
Hi, thanks for the report and for fixing the parsing issue. Can you try and see if #695 fixes the problem?

**Comment by tdesveaux** [comment]
Sorry for the late reply.
I don't think I'll have the time to setup a test env for this before some time.

Will this be in the next Sentry release? If so I can confirm if it solves the `ERROR_NO_MORE_ITEMS / 0x0` issue when we update to it.

**Comment by loewenheim** [comment]
It is already in the current symbolic 9.2.1 :)

I'm reopening this until we can confirm that the problem has been fixed.
