### ISSUE TITLE
Pdb support

### ISSUE THREAD

**Issue by mstange** [getsentry/symbolic#72]
`FatObject` currently does not attempt to support pdb files. Are you interested in adding pdb support?

The [pdb crate](https://crates.io/crates/pdb) seems to have the necessary capabilities: It exposes the guid + age (which form the DebugId) and it provides a symbol iterator. And the [msvc-demangler crate](https://github.com/mstange/msvc-demangler-rust) is shaping up to provide adequate demangling for Windows C++ symbols.

I'm interested in helping with the implementation, if this is deemed to be a desirable addition.

**Comment by jan-auer** [comment]
Hi @mstange, thanks so much for reaching out 👋 . Adding support for PDBs has been on our list for so long now, but we never got around to trying `pdb` and `msvc-demangler`. We'd love some help here (and would of course also contribute back to those crates if necessary). 

Besides adding support to `FatObject`, the next steps would then be to add PDB support to `SymCache` and the `BreakpadCfiWriter`, which are currently not properly abstracted from the debugging format. 

If you like, you can start to put a PR together, or I'll try to make some time soon to get some of the work going. Help is definitely appreciated ❤️
