### ISSUE TITLE
Consider changing `DebugSession::source_by_path()` to `&mut self`

### ISSUE THREAD

**Issue by vaind** [getsentry/symbolic#736]
Hm, given that this is the fn signature of our `DebugSession`, it does make sense to lazily decompress the file contents, and have optional errors there.

I wonder if it might be worth breaking this and making it a `&mut self` fn. That way, the `DebugSession` can maintain an internal cache of already decompressed file contents. It seems a bit suboptimal that we decompress the same file over and over if we have multiple frames that map to the same file.
Though this is a already a problem for our normal sourcebundles.
I wonder if symbolicator itself would even allow this to be `mut`, maybe it wouldn’t like that either.

_Originally posted by @Swatinem in https://github.com/getsentry/symbolic/pull/734#discussion_r1048501989_

**Comment by loewenheim** [comment]
I just had a look,`source_by_path` is only used in one place in symbolicator and it's no problem to get a `&mut DebugSession` there.

**Comment by vaind** [comment]
We can use LazyCell, or ocne_cell once it becomes stabilized: https://github.com/rust-lang/rust/issues/74465#issuecomment-884409256 - it doesn't require a muteble `self` so closing for now.
