### ISSUE TITLE
Incorrect uuid dependency in symbolic-ppdb

### ISSUE THREAD

**Issue by afranchuk** [getsentry/symbolic#770]
### Environment

`symbolic-ppdb v11.1.0`

### Steps to Reproduce

1. Create a new crate with
```
[dependencies]
symbolic-ppdb = "11.1.0"
uuid = "=1.0.0"
```

2. Run `cargo build`.

### Expected Result

Dependencies are fetched and built.

### Actual Result

`symbolic-ppdb` fails to compile.

### Solution

`Uuid::to_bytes_le()` (used in `src/format/streams.rs`) was added in `1.1.0`, so the constraint needs to be updated.

**Comment by Swatinem** [comment]
This is the first time I see someone actually testing with min versions. Since `uuid` is probably not the only offender, I just bumped them all in https://github.com/getsentry/symbolic/pull/771

**Comment by afranchuk** [comment]
It was complete coincidence with a fairly old lockfile. Though it would be nice if e.g. `cargo publish` would test this sort of thing.
