### ISSUE TITLE
How to use `symbolic` to symbolicate a stack trace?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/symbolic#799]
Thanks for the library! Suppose I have `something.so` (with symbols, Android ARM architecture), and some addresses to be symbolicated. How can I use the library to symbolicate them?

I checked https://github.com/getsentry/symbolic/blob/master/examples/addr2line/src/main.rs and it looks promising. However, I do not find equivalent functions at Python side...

**Comment by loewenheim** [comment]
Hi, I'm afraid we don't expose that functionality in the Python bindings. What you can try:

1. Create a symcache file from your debug file using `cargo run -p symcache_debug -- -d <debug file> -c out.sym`
2. Load the symcache file in Python with `SymCache.open`
3. Use `Symcache.lookup` to look up an address

Would that work for you?

**Comment by fzyzcjy** [comment]
@loewenheim Hi thank you for the information! I will try for that and reply soon.

**Comment by fzyzcjy** [comment]
Then I wonder how should I demangle the symbols? It seems it is in Rust API https://github.com/getsentry/symbolic/blob/57246bf463d03dcf992193ed8007887b9a0a2e2d/examples/addr2line/src/main.rs#L17, but searching `demangle` in `py` folder yields nothing

**Comment by loewenheim** [comment]
Yeah demangling unfortunately has no Python bindings.

**Comment by fzyzcjy** [comment]
@loewenheim So will it be supported? Or if I make a PR, will it be merged?

**Comment by loewenheim** [comment]
It used to exist, but we removed it in https://github.com/getsentry/symbolic/pull/730 because we don't want to commit to maintaining those bindings.

**Comment by fzyzcjy** [comment]
Ah I see... Thanks, so I will not PR for that.
