### ISSUE TITLE
Add SourceLink support to SourceBundles

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolic#802]
Right now, `SourceLink` support is limited to PortablePDB files.

We could extend the `SourceBundle` to also support source links, like so:

* Add a new `source_links` property to the sourcebundle `manifest.json` which works similarly to portable pdb.
* When querying files from source bundles, we could first look up the file using the indexed `files` entries as normal
* When no explicit entry in `files` is found, we can do a sourcelink lookup for the provided `path` similar to portable pdb here:

https://github.com/getsentry/symbolicator/blob/56ad31f03071f80849e5db1dfb9b97b08a34174f/crates/symbolicator-service/src/services/sourcemap_lookup.rs#L799-L806

We might restrict this to *read* support only in the beginning, so it would require users to craft such a source bundle / manifest by hand.
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/symbolic/pull/803
- [ ] https://github.com/getsentry/symbolic/pull/804
```

**Comment by loewenheim** [comment]
Source link support for source bundles has landed in `symbolic` 12.3.0.
