### ISSUE TITLE
Deduplicate PDB function entries

### ISSUE THREAD

**Issue by Swatinem** [getsentry/symbolic#808]
We have seen cases in which a PDB contains conflicting / duplicated debug info for the same "physical" addr range.
The assumption is that a linker might do link time identical code folding (ICF), leaving behind the separate debug info for the code that was merged.

This theory was supported by a customer who has confirmed the conflicting functions contain the same (copy-pasted?) code.

We have similar deduplication code already for DWARF, and can implement that for PDB as well.

`addr2line-pdb` is also picking the first matching debug info entry, whereas we are currently picking the last one. But that is just an implementation detail and very much depends on the order in which the linker emits debug info.

**Comment by loewenheim** [comment]
Closing this for now, will reopen when we see more cases.
