### ISSUE TITLE
iOS Crashlytics: Can not Resolving compiler generated crashes

### ISSUE THREAD

**Issue by Doslin** [getsentry/symbolic#838]
### Environment
MacOS(14.1.1 (23B81))

What version are you running? Etc.

### Steps to Reproduce
1. use symbolicatecrash  get converted report 
./[symbolicatecrash](https://github.com/getsentry/symbolic/files/15400082/symbolicatecrash.zip) ./[file-origin-crash-txt](https://gist.github.com/Doslin/d12012fd3710ff6195e799f7a5b766f4#file-origin-crash-txt)  ./[dSYMs.zip](https://github.com/getsentry/symbolic/files/15399759/dSYMs.zip) >  [file-crash-report-by-symbolicatecrash-log](https://gist.github.com/Doslin/d12012fd3710ff6195e799f7a5b766f4#file-crash-report-by-symbolicatecrash-log)
![image](https://github.com/getsentry/symbolic/assets/29807388/42a46a2e-e14e-4083-a809-a60047fb19a3)

2. use symbolic
```rust
fn test_lookup_compiler_generated_crashes() -> Result<(), Error> {
    let buffer = ByteView::open(        "/Users/doude/Downloads/Crash-20240229/test-compiler-generated/dSYMs/GPark.app.dSYM/Contents/Resources/DWARF/GPark",    )?;
    let object = Object::parse(&buffer)?;
    let mut buffer = Vec::new();
    let mut converter = SymCacheConverter::new();
    converter.process_object(&object)?;
    converter.serialize(&mut Cursor::new(&mut buffer))?;
    let symcache = SymCache::parse(&buffer)?;
    let symbols = &symcache.lookup(4486444 as u64).collect::<Vec<_>>()[0];
    let abs_path = symbols
        .file()
        .map(|f| f.full_path())
        .unwrap_or_else(|| "null content".into());
    println!("4486444 result {} {} ", abs_path, symbols.line());

    let symbols = &symcache.lookup(4484944 as u64).collect::<Vec<_>>()[0];
    let abs_path = symbols
        .file()
        .map(|f| f.full_path())
        .unwrap_or_else(|| "null content".into());
    println!("4484944 result {} {} ", abs_path, symbols.line());

    Ok(())
}
```
![image](https://github.com/getsentry/symbolic/assets/29807388/f063b8c4-319f-45c2-b8d5-290437ac564c)

### Expected Result
 compiler generated would be symbol successful with line 70

### Actual Result

What actually happened. Maybe a screenshot/recording? Maybe some logs?

**Comment by Doslin** [comment]
[symbolicatecrash exec](https://github.com/getsentry/symbolic/files/15400082/symbolicatecrash.zip)

**Comment by Swatinem** [comment]
I don’t think the line number of `<compiler generated>` code really matters. Does it at least output the correct function name (adjusted for Swift mangling)?
