### ISSUE TITLE
Support for wasm exception handling legacy proposal

### ISSUE THREAD

**Issue by trzeciak** [getsentry/symbolic#850]
Symbolic supports wasm files without exceptions, but there are problems with wasm files with exceptions.  

As an introduction _(we may not use exceptions at all xD)_: we can use [legacy exceptions](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/legacy/Exceptions.md) (it has been in browsers for 3 years), we can use (new/current) [exceptions handling purposal](https://github.com/WebAssembly/exception-handling/blob/main/proposals/exception-handling/Exceptions.md) (end of last year).

The problem with the current exceptions handler proposal is its still low support on the customers side. Therefore, in this issue I would like to raise the topic of support for legacy proposals.

Having a sample main file that throws an exception:
```cpp
//  example_exception.cpp
#include <stdio.h>
#include <stdexcept>
int main() {
    printf("hello..\n");
    throw std::runtime_error("Kerfufle");
    printf("world!\n");
    return 0;
}
```

And compile it (using emscripten with support for exceptions) and try validate it (using symbolic `object_debug`), we got this error:
```sh
$ emcc -fwasm-exceptions -o example_exception.wasm example_exception.cpp # latest (v3.1.61)
$ ./symbolic/object_debug example_exception.wasm # latest (master)
Inspecting example_exception.wasm
File format: wasm
Objects:
 - Error: invalid wasm file
   caused by unimplemented validation of deprecated opcode (at offset 0x252)
```
This happens because the validator in the wasmparser library has stopped supporting legacy-exceptions (https://github.com/bytecodealliance/wasm-tools/pull/1333).

When I restore support for deprecated opcode: https://github.com/trzeciak/wasm-tools/commit/871dbcba98ad05dc3ec55d1ed91a948a2b0f9c35, it allows to symbolic work correctly:
```sh
$ ./patched/object_debug example_exception.wasm # master+revert-deprecated-try-catch-catch_all-opcodes
Inspecting example_exception.wasm
File format: wasm
Objects:
 - wasm32: 00000000-0000-0000-0000-000000000000
   code id:      -
   object kind:  library
   load address: 0x0
   symbol table: true
   debug info:   false
   unwind info:  false
   is malformed: false
```

If I understand correctly:
* legacy exceptions have been well-handled by most browsers for some time,
* browsers will handle both types of exceptions for some time during the migration,
* at least until then wasmparser will support processing these opcodes,

to ensure the greatest coverage for our customers, it may be a good idea to use the legacy-exceptions for today and switch to the new exceptions after some time.

----

### The question is, could we update the symbolic code to support legacy and new exception-handling?  

I did some preliminary research and it looks like the changes should be made around [symbolic-debuginfo/src/wasm/parser.rs](https://github.com/getsentry/symbolic/blob/master/symbolic-debuginfo/src/wasm/parser.rs), replacing wasmparser 'validator' with 'parser'.

Do you think this makes sense, and is it worth preparing a pull-request that ensures this (although I'm not sure I can do it myself)?

**Comment by loewenheim** [comment]
A PR for this would be welcome, yes.

**Comment by trzeciak** [comment]
Okay, I'll wait for the answer to this question: https://github.com/bytecodealliance/wasm-tools/issues/1653,
because restoring it in the `wasmparser` behind the flag seems easier to implement.

**Comment by trzeciak** [comment]
It seems to be working, thanks to others for their help, done.
