### ISSUE TITLE
How to support demangle in Swift 5.10 and generate a Python library

### ISSUE THREAD

**Issue by fantexi023** [getsentry/symbolic#852]
Hello, we found that Symbol has removed the relevant interface of swift-demagle in 11.0.0, and Symbol has not upgraded Swift-demangle for a long time. 

We have been using Symbol's python library ( [https://pypi.org/project/symbolic/10.0.0/#description ](https://pypi.org/project/symbolic/10.0.0/#description)), and recently we want to upgrade swift5.10 ourselves. 

I want to know how you built the python library before? Did you use a build tool similar to maturin to encapsulate the dynamic link library built in Rust as a Python library? Looking forward to your reply, so that we can continue to enjoy the convenience of Symbol. 

Thanks.

**Comment by Swatinem** [comment]
The Python bindings were created way before `maturin` or `pyo3` existed.
Maintaining those had become a maintenance burden, and we are aiming towards removing as much of the Python binding code as we can, as we are also not using any of that ourselves directly anymore.

If you want to have python bindings to `symbolic-demangle`, I would suggest you build a pyo3/maturin wrapper yourself, I would argue it is fairly straight forward to do.
