### ISSUE TITLE
detect_language() is wrong

### ISSUE THREAD

**Issue by handy-sun** [getsentry/symbolic#867]
### Environment

symbolic-demangle = { version = "12.11.0" }
symbolic-common = { version = "12.11.0" }

### Steps to Reproduce

just run `cargo test` for folllowing code
```rust
#[cfg(test)]
mod tests {
    use symbolic_common::{Language, Name};
    use symbolic_demangle::{Demangle, DemangleOptions};
    const DEM_OPT: DemangleOptions = DemangleOptions::name_only().parameters(true);
    #[test]
    fn detect_language() {
        assert_eq!(Name::from("_ZN7TdhData12pcmStateListE").demangle(DEM_OPT), Some("TdhData::pcmStateList".to_string()));
        assert_eq!(Name::from("_ZN7TdhData12pcmStateListE").detect_language(), Language::Cpp);
    }
}
```

### Expected Result

test passwd

### Actual Result

test failed
```
assertion `left == right` failed
  left: Rust
 right: Cpp
```

But the symbol was compiled by g++, why?

![Image](https://github.com/user-attachments/assets/6b1106a7-8f6d-4942-b8e9-3a939f910a20)

**Comment by handy-sun** [comment]
Thank you for your reply, I have also noticed this line of code.
But my future plan for my project is to be able to distinguish the symbol which language to use.
In fact, `cpp_demangle` and `rustc-demangle` i both used now, and i found some thing confused:

```rust
   #[test]
   fn demangle() {
        ....
        let origin = "TdhData::pcmStateList";
        assert!(rustc_demangle::try_demangle("_ZN7TdhData12pcmStateListE").is_ok());
        assert_eq!(rustc_demangle::demangle("_ZN7TdhData12pcmStateListE").as_str(), origin);
    }
```
test failed and output:
```
assertion `left == right` failed
  left: "_ZN7TdhData12pcmStateListE"
 right: "TdhData::pcmStateList"
```

Does this means that the `assert!` macro passed, but in reality, this symbol cannot be demangled by rust_demangle?

**Comment by loewenheim** [comment]
No, I think `rustc_demangle` is being slightly confusing here. `Demangle::as_str` returns the _mangled_ name. If you want to see the demangled one, you can use the `Display` impl, e.g. 
```
println("{}", rustc_demangle::try_demangle("_ZN7TdhData12pcmStateListE").unwrap());
```
or with `to_string`. But yeah, `as_str` and `to_string` returning completely different things is a strange decision, IMO.

**Comment by handy-sun** [comment]
Okay, does this mean that symbols like this cannot be completely determined which language (Rust and CPP) they were compiled into？

**Comment by loewenheim** [comment]
Correct. Both Rust and C++ could produce that mangled name, so it's not possible to tell with certainty where it came from just from the name.

**Comment by handy-sun** [comment]
Thank you again for your answer！
